thulab/iot-benchmark

- conf/config.properties
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/App.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/measurement/Measurement.java
> add output

- src/main/java/cn/edu/tsinghua/iotdb/benchmark/measurement/Measurement.java
> add more output config

- conf/config.properties
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/App.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/client/Client.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/client/OperationController.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/client/RealDatasetClient.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/client/SyntheticClient.java
> start clients test simultaneously

- src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/influxdb/InfluxDB.java
> add query impl for influxdb

- src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/DBFactory.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/timescaledb/TimescaleDB.java
> impl timescaledb refactor interface

- pom.xml
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/kairosdb/KairosDB.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/workload/RealDatasetWorkLoad.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/workload/query/impl/AggValueQuery.java
实现了kairosDB的查询相关接口。
注意1：kairosDB的查询在过滤条件为“>”时过滤条件为必须大于等于0。
注意2：在真实数据集下的查询必须设置时间范围。
> impl query interface for kairosDB

- benchmark.sh
- iotdbconf/fit/iotdb-engine.properties
- iotdbconf/fit/iotdb-env.sh
change iotdb conf to default setting in branch "Iotdb qa"
an fix a wrong iotdb path in benchmark.sh
>  change iotdb conf to default setting in branch "Iotdb qa"

- ciscripts/compare-branch.sh
- cli-benchmark.sh
change folder name from iotdb to server
> change folder name from iotdb to server

- src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/DBWrapper.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/workload/schema/DeviceSchema.java
I think the previous algorithm is incorrect.
The new algo can guarantee that different client operates different storage group
> change the algo about which group that a device belongs to: deviceId%total_group

- README.md
Change List:
Add table of contents in README.md
> [Doc] Add Table of Contents in README

- README.md
- conf/config.properties
- conf/logback.xml
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/App.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/client/BaseClient.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/client/Client.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/client/QueryRealDatasetClient.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/client/SyntheticClient.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/conf/Config.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/conf/ConfigDescriptor.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/function/Function.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/measurement/Diagnosis.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/measurement/DiagnosisItem.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/measurement/Measurement.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/measurement/Status.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/DBWrapper.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/fakedb/FakeDB.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/influxdb/InfluxDB.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/iotdb/IoTDB.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/kairosdb/KairosDB.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/timescaledb/TimescaleDB.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/workload/SingletonWorkload.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/workload/SyntheticWorkload.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/workload/schema/DeviceSchema.java
- src/test/java/cn/edu/tsinghua/iotdb/benchmark/distribution/PoissonDistributionTest.java
- src/test/java/cn/edu/tsinghua/iotdb/benchmark/workload/SyntheticWorkloadTest.java
- src/test/java/cn/edu/tsinghua/iotdb/benchmark/workload/schema/DeviceSchemaTest.java
Change List:
1. Use workload value buffer for more accurate ```elapseRate``` calculation in ingestion test.
2. Remove the ```accRate``` in the ```Result Matrix```
3. Output test progress log at fixed interval to prevent too much log which may affect the test result(elapse time).
4. Unify the timing to the DBWrapper level instead of inside each DB's implementation
5. Add a Diagnosis class for time cost evaluation.
6. Update README
7. Fix the format of result issue #34
> Fix the elapseRate in Ingestion Test and Polish Existing Code 

- benchmark.sh
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/workload/SyntheticWorkload.java
> Fix Overflow Ingestion

- README.md
> Fix REAMDE Document

- conf/README.md
- conf/config.properties
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/client/BaseClient.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/conf/Config.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/conf/ConfigDescriptor.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/conf/Constants.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/workload/schema/DeviceSchema.java
1. Add unbalanced insertion workload for testing dynamic config
2. Add OPS control of BaseClient to control actual writing speed
> Unbalanced workload

- src/main/java/cn/edu/tsinghua/iotdb/benchmark/workload/SyntheticWorkload.java
Use parameter NUMBER_OF_DECIMAL_DIGIT to control TEXT type data length.
> Add text type data length control

- conf/config.properties
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/workload/SyntheticWorkload.java
Make the generated timestamps can be controlled by random seed.
> fix(getCurrTimeStamp):

- pom.xml
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/iotdb/IoTDBSession.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/workload/schema/DeviceSchema.java
- src/test/java/cn/edu/tsinghua/iotdb/benchmark/distribution/PoissonDistributionTest.java
- src/test/java/cn/edu/tsinghua/iotdb/benchmark/workload/schema/DeviceSchemaTest.java
please merge this  PR when you want to let the master branch supporting v0.10
> support IoTDB v0.10

- conf/config.properties
- pom.xml
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/conf/Constants.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/DBFactory.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/taosdb/TaosDB.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/workload/SyntheticWorkload.java
> support taosdb for master branch

- conf/config.properties
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/conf/Config.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/conf/ConfigDescriptor.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/model/KairosDataModel.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/DBUtil.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/IDatabase.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/influxdb/InfluxDB.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/iotdb/IoTDB.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/iotdb/IoTDBSession.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/kairosdb/KairosDB.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/taosdb/TaosDB.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/timescaledb/TimescaleDB.java
discard data_type parameter in config.properties and only use INSERT_DATATYPE_PROPORTION instead.
> discard data_type parameter in config.properties and only use INSERT_DATATYPE_PROPORTION instead.

- src/main/java/cn/edu/tsinghua/iotdb/benchmark/model/InfluxDataModel.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/DBUtil.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/influxdb/InfluxDB.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/iotdb/IoTDBSession.java
- src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/taosdb/TaosDB.java
It is strange that we just generate double value.... and then convert it to other data formats......
As the program works like this, I have to follow the similar logic and fix the bugs in influxdb and make sure all TSDB using the uniform way.
> use the uniform way to convert all double values to wanted data type

- conf/config.properties
- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/client/BaseClient.java
- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/conf/Config.java
- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/conf/ConfigDescriptor.java
- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/measurement/persistence/mysql/MySqlRecorder.java
- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/DBUtil.java
- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/DBWrapper.java
- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/IDatabase.java
- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/fakedb/FakeDB.java
- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/influxdb/InfluxDB.java
- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/kairosdb/KairosDB.java
- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/opentsdb/OpenTSDB.java
- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/taosdb/TaosDB.java
- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/timescaledb/TimescaleDB.java
- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/workload/IWorkload.java
- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/workload/RealDatasetWorkLoad.java
- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/workload/SyntheticWorkload.java
- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/workload/ingestion/Batch.java
- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/workload/schema/DeviceSchema.java
- iotdb-0.09/src/main/java/cn/edu/tsinghua/iotdb/benchmark/iotdb009/IoTDB.java
- iotdb-0.10/src/main/java/cn/edu/tsinghua/iotdb/benchmark/iotdb010/IoTDB.java
- iotdb-0.11/src/main/java/cn/edu/tsinghua/iotdb/benchmark/iotdb011/DoubleIOTDB.java
- iotdb-0.11/src/main/java/cn/edu/tsinghua/iotdb/benchmark/iotdb011/IoTDB.java
- iotdb-0.11/src/main/java/cn/edu/tsinghua/iotdb/benchmark/iotdb011/IoTDBSession.java
conf/config.properties新增参数IS_SENSOR_TS_ALIGNMENT，默认值是true。
IS_SENSOR_TS_ALIGNMENT为true，一个device下每条记录的各 sensor 采集时间戳对齐
IS_SENSOR_TS_ALIGNMENT为false，一个device下各 sensor 时间戳不对齐，每次只写入一个 sensor 的一个点
支持的数据库:
#IoTDB
#InfluxDB
#KairosDB
#TimescaleDB
#TaosDB
> 一个device下各 sensor 时间戳不对齐，每次只写入一个 sensor 的一个点

- iotdb-0.11/src/main/java/cn/edu/tsinghua/iotdb/benchmark/iotdb011/IoTDBSessionPool.java
- iotdb-0.12/pom.xml
this PR just fixes the compiler error. 
But, testing the text data type data may have errors.
> fix compiler error of iotdb 0.11 and 0.12

- configuration/conf/config.properties
- influxdb-2.0/config.properties
- influxdb-2.0/src/main/java/cn/edu/tsinghua/iotdb/benchmark/influxdb2/InfluxDB.java
fix bug of align sensor in influxdb-2.0
> fix bug of align sensor

- influxdb-2.0/README.md
Update influxdb2.0 quickstart README.md
> Update influxdb2.0 quickstart README.md

- iotdb-0.12/src/main/java/cn/edu/tsinghua/iotdb/benchmark/iotdb012/IoTDBClusterSession.java
- iotdb-0.12/src/main/java/cn/edu/tsinghua/iotdb/benchmark/iotdb012/IoTDBSession.java
- iotdb-0.13/src/main/java/cn/edu/tsinghua/iotdb/benchmark/iotdb013/IoTDBClusterSession.java
- iotdb-0.13/src/main/java/cn/edu/tsinghua/iotdb/benchmark/iotdb013/IoTDBSession.java
fix some unclose of sessionDataset.
> [IOTDB-2314] Fix/session verification

- README-cn.md
- README.md
- kairosdb/src/main/java/cn/edu/tsinghua/iotdb/benchmark/kairosdb/KairosDB.java
1. fix the no protocol failure during insert
2. fix the typo: kariosdb -> kairosdb
> [KairosDB] bugfix & typo fix

- configuration/conf/config.properties
- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/conf/Config.java
- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/conf/ConfigDescriptor.java
- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/conf/Constants.java
- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/schema/MetaDataSchema.java
- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/schema/MetaUtil.java
- mssqlserver/src/main/java/cn.edu.tsinghua.iotdb.benchmark.mssqlserver/MsSQLServerDB.java
- sqlite/src/main/java/cn/edu/tsinghua/iotdb/benchmark/sqlite/SqliteDB.java
add GROUP_NAME_PREFIX、DEVICE_NAME_PREFIX、SENSOR_NAME_PREFIX parameters into config.properties
> [name] move name to parameters

- configuration/conf/config.properties
- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/conf/Config.java
- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/conf/ConfigDescriptor.java
- iotdb-0.13/src/main/java/cn/edu/tsinghua/iotdb/benchmark/iotdb013/IoTDB.java
- iotdb-0.13/src/main/java/cn/edu/tsinghua/iotdb/benchmark/iotdb013/IoTDBClusterSession.java
- iotdb-0.13/src/main/java/cn/edu/tsinghua/iotdb/benchmark/iotdb013/IoTDBSession.java
See more details: https://issues.apache.org/jira/browse/IOTDB-2710
> [IOTDB-2710] Feature/debug query

- iotdb-0.13/src/main/java/cn/edu/tsinghua/iotdb/benchmark/iotdb013/IoTDB.java
- iotdb-0.13/src/main/java/cn/edu/tsinghua/iotdb/benchmark/iotdb013/IoTDBSession.java
- iotdb-0.13/src/main/java/cn/edu/tsinghua/iotdb/benchmark/iotdb013/IoTDBSessionBase.java
https://issues.apache.org/jira/browse/IOTDB-2746?filter=-1
https://issues.apache.org/jira/browse/IOTDB-2751?filter=-1
> [IOTDB-2746][IOTDB-2751] remove internalNode from template

- configuration/conf/config.properties
(cherry picked from commit 783781b9d1ca40e1b50fbcab059831c2dbbfe612)
> [config] change default mode to iotdb-0.13

- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/extern/CSVSchemaWriter.java
see https://issues.apache.org/jira/browse/IOTDB-2953
> [IOTDB-2953] IoTDB benchmark writeSchema bug

- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/schema/MetaDataSchema.java
- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/schema/schemaImpl/GenerateMetaDataSchema.java
- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/schema/schemaImpl/RealMetaDataSchema.java
- iotdb-0.12/src/main/java/cn/edu/tsinghua/iotdb/benchmark/iotdb012/IoTDB.java
- iotdb-0.13/src/main/java/cn/edu/tsinghua/iotdb/benchmark/iotdb013/IoTDB.java
[schema] fix the problem that some timeseries will be created before the creatation of storage group.
> [schema] fix the problem that some timeseries will be created before the creatation of storage group.

- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/client/SchemaClient.java
- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/DBWrapper.java
- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/IDatabase.java
- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/fakedb/FakeDB.java
- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/utils/TimeUtils.java
- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/workload/GenerateDataWorkLoad.java
- iginx/src/main/java/cn/edu/tsinghua/iotdb/benchmark/iginx/IginX.java
- influxdb-2.0/src/main/java/cn/edu/tsinghua/iotdb/benchmark/influxdb2/InfluxDB.java
- influxdb/src/main/java/cn/edu/tsinghua/iotdb/benchmark/influxdb/InfluxDB.java
- iotdb-0.09/src/main/java/cn/edu/tsinghua/iotdb/benchmark/iotdb009/IoTDB.java
- iotdb-0.10/src/main/java/cn/edu/tsinghua/iotdb/benchmark/iotdb010/IoTDB.java
- iotdb-0.11/src/main/java/cn/edu/tsinghua/iotdb/benchmark/iotdb011/IoTDB.java
- iotdb-0.11/src/main/java/cn/edu/tsinghua/iotdb/benchmark/iotdb011/IoTDBSessionPool.java
- iotdb-0.12/src/main/java/cn/edu/tsinghua/iotdb/benchmark/iotdb012/IoTDB.java
- iotdb-0.12/src/main/java/cn/edu/tsinghua/iotdb/benchmark/iotdb012/TemplateSchema.java
- iotdb-0.12/src/main/java/cn/edu/tsinghua/iotdb/benchmark/iotdb012/TimeseriesSchema.java
- iotdb-0.13/src/main/java/cn/edu/tsinghua/iotdb/benchmark/iotdb013/IoTDB.java
- iotdb-0.13/src/main/java/cn/edu/tsinghua/iotdb/benchmark/iotdb013/TimeseriesSchema.java
- kairosdb/src/main/java/cn/edu/tsinghua/iotdb/benchmark/kairosdb/KairosDB.java
- mssqlserver/src/main/java/cn.edu.tsinghua.iotdb.benchmark.mssqlserver/MsSQLServerDB.java
- opentsdb/src/main/java/cn/edu/tsinghua/iotdb/benchmark/opentsdb/OpenTSDB.java
- pi/src/main/java/cn/edu/tsinghua/iotdb/benchmark/piarchive/PIArchive.java
- questdb/src/main/java/cn/edu/tsinghua/iotdb/benchmark/questdb/QuestDB.java
- sqlite/src/main/java/cn/edu/tsinghua/iotdb/benchmark/sqlite/SqliteDB.java
- tdengine/src/main/java/cn/edu/tsinghua/iotdb/benchmark/tdengine/TDengine.java
- timescaledb/src/main/java/cn/edu/tsinghua/iotdb/benchmark/timescaledb/TimescaleDB.java
- victoriametrics/src/main/java/cn.edu.tsinghua.iotdb.benchmark.victoriametrics/VictoriaMetrics.java
1. support to get more specific register schema time.
2. optimize the implementation of schema module.
> Optimize schema module in high concurrency.

- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/conf/Config.java
See more details: https://issues.apache.org/jira/browse/IOTDB-3712
> [IOTDB-3712] update show config

- core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/conf/ConfigDescriptor.java
https://issues.apache.org/jira/browse/IOTDB-4264
> [IOTDB-4264] correct spotless-check error

- tdengine-3.0/src/main/java/cn/edu/tsinghua/iot/benchmark/tdengine3/TDengine.java
- tdengine/src/main/java/cn/edu/tsinghua/iot/benchmark/tdengine/TDengine.java
Fix the generation of timestamp in taos test into correct way
> [IOTDB-5221] Fix the generation of timestamp in taos test

- configuration/conf/config.properties
- core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/Config.java
- core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/ConfigDescriptor.java
- tdengine-3.0/src/main/java/cn/edu/tsinghua/iot/benchmark/tdengine3/TDengine.java
- tdengine/src/main/java/cn/edu/tsinghua/iot/benchmark/tdengine/TDengine.java
1. Fix the timestamp failure when insert
2. Support create database and drop database
3. Fix the concurrency problem of registering
> [IOTDB-5241] Fix the test of TDengine

- core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/Config.java
https://issues.apache.org/jira/browse/IOTDB-5272
> [IOTDB-5272] Fix the generation of sensor

- core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/Config.java
https://issues.apache.org/jira/browse/IOTDB-5272
> [IOTDB-5272] Fix the generation of sensor type

- iotdb-1.0/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb100/IoTDBSession.java
https://issues.apache.org/jira/browse/IOTDB-5490
> [IOTDB-5490] Fix vector implementation in by records interface

- core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/Constants.java
- core/src/main/java/cn/edu/tsinghua/iot/benchmark/tsdb/DBFactory.java
- core/src/main/java/cn/edu/tsinghua/iot/benchmark/tsdb/enums/DBSwitch.java
- core/src/main/java/cn/edu/tsinghua/iot/benchmark/tsdb/enums/DBType.java
- core/src/main/java/cn/edu/tsinghua/iot/benchmark/tsdb/self/SelfCheck.java
Add `SelfCheck` DB to check the generation of data
> [IOTDB-5537] Add Self Check

- core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/ConfigDescriptor.java
https://issues.apache.org/jira/browse/IOTDB-5540
> [IOTDB-5540] Support 1.0 version verification mode

- core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/Config.java
- core/src/main/java/cn/edu/tsinghua/iot/benchmark/schema/MetaDataSchema.java
- core/src/main/java/cn/edu/tsinghua/iot/benchmark/schema/schemaImpl/RealMetaDataSchema.java
- core/src/main/java/cn/edu/tsinghua/iot/benchmark/source/CSVDataReader.java
- core/src/main/java/cn/edu/tsinghua/iot/benchmark/source/CSVSchemaReader.java
- core/src/main/java/cn/edu/tsinghua/iot/benchmark/source/CopyDataReader.java
- core/src/main/java/cn/edu/tsinghua/iot/benchmark/workload/RealDataWorkLoad.java
https://issues.apache.org/jira/browse/IOTDB-5666
> [IOTDB-5666] Support less format naming of sensor in external dataset

- iotdb-1.1/pom.xml
- iotdb-1.1/src/assembly/assembly.xml
- iotdb-1.1/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb100/IoTDB.java
- iotdb-1.1/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb100/IoTDBClusterSession.java
- iotdb-1.1/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb100/IoTDBSession.java
- iotdb-1.1/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb100/IoTDBSessionBase.java
- iotdb-1.1/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb100/SingleNodeJDBCConnection.java
- iotdb-1.1/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb100/TimeseriesSchema.java
- iotdb-1.1/src/main/test/cn/edu/tsinghua/iot/benchmark/IoTDB110TestEntrance.java
- pom.xml
1. Update dependency of 0.13.x IoTDB to 0.13.4, checkout `rel/iotdb_0.13.3` branch to locate old code.
2. Add `iotdb-1.1` module
> [Dependency] Update the dependency in 0.13.x and Add 1.1 IoTDB Testing 

- iotdb-1.0/pom.xml
- iotdb-1.0/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb100/IoTDB.java
- iotdb-1.0/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb100/IoTDBClusterSession.java
- iotdb-1.0/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb100/IoTDBSession.java
Reverts thulab/iot-benchmark#333
> Revert "Update doc and constant"

- core/src/main/java/cn/edu/tsinghua/iot/benchmark/schema/schemaImpl/DeviceSchema.java
- iotdb-1.1/pom.xml
- iotdb-1.1/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb110/IoTDB.java
https://apache-iotdb.feishu.cn/docx/O7rZdYC6No8dtExCM7ncRl8LnJe
> Activate template during the stage of registering schema 

- iotdb-1.1/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb110/IoTDBSessionBase.java
https://apache-iotdb.feishu.cn/docx/HrXYdvlauoVJdBxE8wPcXWXHn9d
> Optimize TEXT insertion

- core/src/main/java/cn/edu/tsinghua/iot/benchmark/client/DataClient.java
> Fix processing display problem 

- configuration/conf/config.properties
- core/src/main/java/cn/edu/tsinghua/iot/benchmark/workload/GenerateDataWorkLoad.java
- core/src/main/java/cn/edu/tsinghua/iot/benchmark/workload/SingletonWorkDataWorkLoad.java
- core/src/main/java/cn/edu/tsinghua/iot/benchmark/workload/SyntheticDataWorkLoad.java
In formal implementation, the data of same timestamp are same even if in different devices. This pr fix this problem
> Shuffle data when generate

- README.md
> Remove duplicated `in addition` in REDAME.

- iotdb-0.13/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb013/IoTDB.java
Optimized the name of an exception
> Optimized an exception

- README-cn.md
> fix doc broken ref link

- core/src/main/java/cn/edu/tsinghua/iot/benchmark/client/real/RealDataSetWriteClient.java
The op interval function is only implemented in GenerateDataMixClient currently. This PR will complete this function on all Clients
> Complete op interval function

- configuration/benchmark.sh
> Add startup prompt statement

- core/src/main/java/cn/edu/tsinghua/iot/benchmark/mode/BaseMode.java
- core/src/main/java/cn/edu/tsinghua/iot/benchmark/workload/GenerateDataWorkLoad.java
It is suspected that a task in the Timer is blocked, affecting the execution of other tasks.
> Replace Timer with ScheduledExecutorService so that scheduled tasks can be executed in parallel.

- core/src/main/java/cn/edu/tsinghua/iot/benchmark/entity/Batch/Batch.java
> Fix pointNum

- kairosdb/pom.xml
- tdengine/pom.xml
Fix issue #297 by update dependency org.apache.httpcomponents:httpclient:4.5.13 @FLOW4215 @xiaoyekanren
> Fix CVE dependency issue

- tdengine/pom.xml
fixup https://github.com/thulab/iot-benchmark/commit/b315c494633145ff477d319675ab125460ec4ac5
> Fix syntax errors in the pom file

- iotdb-2.0/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb200/IoTDB.java
- iotdb-2.0/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb200/ModelStrategy/IoTDBModelStrategy.java
- iotdb-2.0/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb200/ModelStrategy/TableStrategy.java
- iotdb-2.0/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb200/ModelStrategy/TreeStrategy.java
Divide the query statement into three parts: SELECT, FROM and WHERE (time, value)
- SELCET
- - getSimpleQuerySqlHead
- - getAggQuerySqlHead
- FROM 
- - addFromClause
- WHERE
- - addWhereClause (boolean addTime,
boolean addValue,
long start,
long end,
List<DeviceSchema> deviceSchemas,
int valueThreshold,
StringBuilder builder)
- - addAggWhereClause (boolean addTime,
boolean addValue,
long start,
long end,
List<DeviceSchema> deviceSchemas,
int valueThreshold,
StringBuilder builder)
Benchmark Q1-Q11 iotdb SQL
https://laj14weh3dn.feishu.cn/wiki/QAvFw49A2iIcUPkgmCdcZTwdnL4?from=from_copylink
> support Q4-Q8 and Q11 for table mode.

- core/src/main/java/cn/edu/tsinghua/iot/benchmark/workload/GenerateQueryWorkLoad.java
Use the same strategy to ensure that the device`s numbers for precise value queries in the tree model and table model.
> Ensure the equivalence of SQL for precise value queries in tree model and table model.

- iotdb-2.0/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb200/DMLStrategy/SessionStrategy.java
- iotdb-2.0/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb200/ModelStrategy/TableStrategy.java
> Fix okPointNum statistics for table models.

- iotdb-1.3/pom.xml
https://github.com/thulab/iot-benchmark/actions/runs/12247747619/job/34166141286
> Fix iotdb-1.3 compile error

- core/src/main/java/cn/edu/tsinghua/iot/benchmark/measurement/Measurement.java
- core/src/main/java/cn/edu/tsinghua/iot/benchmark/mode/BaseMode.java
- 计算 Latency 时，添加对负值的特判以及日志的输出
- 计算分位数时前，输出均值为负数的质心
> Print logs when Latency is negative

- core/src/main/java/cn/edu/tsinghua/iot/benchmark/mode/BaseMode.java
> fix ConcurrentModificationException by replacing HashMap with ConcurrentHashMap

- core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/Config.java
> Remove quotes from 'IS_COPY_MODE' and 'ANOMALY_TIMES'.

- iotdb-2.0/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb200/ModelStrategy/TableStrategy.java
> Fix registration table issue.

- core/src/main/java/cn/edu/tsinghua/iot/benchmark/measurement/Measurement.java
**operationLatencyDigest.get(operation).size()**  reflects the number of inserted values, not the number of centroids in the TDigest.
> Fix NPE by checking centroid count instead of data count before calling quantile()
