thulab/iot-benchmark

src/main/java/cn/edu/tsinghua/iotdb/benchmark/conf/Config.java

将redd数据集中的field 由value改变为v（ps：value在iotdb中是保留字段，不可以使用）

change field name in redd dataset

---

conf/config.properties
src/main/java/cn/edu/tsinghua/iotdb/benchmark/App.java
src/main/java/cn/edu/tsinghua/iotdb/benchmark/client/BaseClient.java
src/main/java/cn/edu/tsinghua/iotdb/benchmark/client/QueryRealDatasetClient.java
src/main/java/cn/edu/tsinghua/iotdb/benchmark/client/SyntheticBaseClient.java
src/main/java/cn/edu/tsinghua/iotdb/benchmark/client/SyntheticClient.java
src/main/java/cn/edu/tsinghua/iotdb/benchmark/conf/Config.java
src/main/java/cn/edu/tsinghua/iotdb/benchmark/conf/ConfigDescriptor.java
src/main/java/cn/edu/tsinghua/iotdb/benchmark/conf/Constants.java
src/main/java/cn/edu/tsinghua/iotdb/benchmark/workload/IWorkload.java
src/main/java/cn/edu/tsinghua/iotdb/benchmark/workload/RealDatasetWorkLoad.java
src/main/java/cn/edu/tsinghua/iotdb/benchmark/workload/SyntheticWorkload.java

实现了真实数据集的查询负载，在testWithDefaultPath模式下，每个客户端会执行LOOP次查询，每种查询的查询条件相同：
>需要配置REAL_QUERY_START_TIME, REAL_QUERY_STOP_TIME做为时间范围, DATA_SET 以及 testWithDefaultPath模式下查询有关参数。
>在testWithDefaultPath模式下,设备的名字是1，2，3....
>OPERATION_PROPORTION=2:0:0:0:0:0:0:0:0中的写入比例必须为0，有参数检查
执行结果：
>写入REDD数据集的2个设备，每个设备18个点
>查询单timeseries

imp query workload for real data

---

pom.xml
src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/iotdb/IoTDB.java

1、去掉了pom文件中没有用到的cn.edu.tsinghua.iotdb下的jdbc引用，有2个jdbc容易造成误解
2、在IoTDB.java类的查询方法中增加了catch throwable，这样当由于jdbc版本使用错误等造成抛出Throwable时更容易定位问题

remove useless jdbc version in pom and catch throwable exception

---

src/main/java/cn/edu/tsinghua/iotdb/benchmark/workload/schema/DataSchema.java
src/main/java/cn/edu/tsinghua/iotdb/benchmark/workload/schema/DeviceSchema.java
src/test/java/cn/edu/tsinghua/iotdb/benchmark/workload/schema/DataSchemaTest.java
src/test/java/cn/edu/tsinghua/iotdb/benchmark/workload/schema/DeviceSchemaTest.java

若设置参数IS_CLIENT_BIND=true，则每个客户端只负责某几个设备的写入负载，且每个设备的写入负载仅分配给一个客户端：
> 在之前的实现中,若DEVICE_NUM不能被CLIENT_NUM整除，则剩下的余数个DEVICE全部分配给最后一个client，造成client之间负载不平衡的现象。而写入时间统计的是最后一个客户端的完成时间，这样当设备数不能被客户端数目整除的时候，测试结果不准。
> 此pr调整了设备和客户端之间的对应策略，不管设备数能否被客户端数目整除，均保证不同的客户端负责写入的设备数目最多相差1个。

balance workload among multiple client.

---

README.md
conf/config.properties
src/main/java/cn/edu/tsinghua/iotdb/benchmark/measurement/Measurement.java
src/main/java/cn/edu/tsinghua/iotdb/benchmark/measurement/enums/Metric.java
src/main/java/cn/edu/tsinghua/iotdb/benchmark/tsdb/iotdb/IoTDB.java

Change List:
1. Add Streamlib library to use T-Digest Algorithm to Calculate Quantiles avoiding OOM Error when operation number is very big. AKA. fix issue #95 
2. Update README.md
3. Replace statistic MID_AVG with P999

Use T-Digest Algorithm to Calculate Quantiles to avoid OOM Error 

---

core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/measurement/enums/SingleTestMetrics.java
core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/measurement/persistence/iotdb/IotdbRecorder.java

1.Remove the device for each thread.
Add a column to the "operation" device to save thread info.

Change the device structure definition that stores all clients test results

---

README.md

In this version of README.md, I have added the modification to clientsysteminfo.properties and the 'operation_proportion' parameter in config.properties to facilitate users to correctly use IoTDB-Benchmark for benchmarking

add some lose step

---

iotdb-0.11/src/main/java/cn/edu/tsinghua/iotdb/benchmark/iotdb011/IoTDB.java
iotdb-0.12/src/main/java/cn/edu/tsinghua/iotdb/benchmark/iotdb012/IoTDB.java

For IoTDB, current cleanup method is implemented by "delete timeseries root.test"
When there are many timeseries already exist in db after a round of insertion test, this cleanup method will block many many minutes.
Because In IoTDB, "delete timeseries" is implemented by delete all timeseries of all storage groups, not the storage group itself, which will create a modfile for every tsfile.  These modfiles will be merged on compaction tasks.
This PR will fix this by using "delete storage group"  instead of "delete timeseries".

optimize IoTDB's cleanup

---

configuration/conf/config.properties
core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/conf/Config.java
core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/conf/ConfigDescriptor.java

Some config parameters in config.properties are not in use, so remove it
/** Maximum number of output items in conditional query with limit */
private int QUERY_LIMIT_N = 1;
/** The offset in conditional query with limit */
private int QUERY_LIMIT_OFFSET = 0;
/** Maximum number of output sequences */
private int QUERY_SLIMIT_N = 1;
/** Offset of output sequences */
private int QUERY_SLIMIT_OFFSET = 0;

Remove useless parameters

---

configuration/conf/config.properties
core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/client/Client.java
core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/client/TimeClient.java
core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/client/generate/GenerateDataDeviceClient.java
core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/client/generate/GenerateDataMixClient.java
core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/client/generate/GenerateDataWriteClient.java
core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/client/real/RealDataSetQueryClient.java
core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/client/real/RealDataSetWriteClient.java
core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/conf/Config.java
core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/conf/ConfigDescriptor.java
core/src/main/java/cn/edu/tsinghua/iotdb/benchmark/mode/BaseMode.java

Add TEST_MAX_TIME parameters into benchmark to control the max test time.
if TEST_MAX_TIME = 0, there are no control, so benchmark will run all test.
if TEST_MAX_TIME not zero, benchmark will do loop no more than TEST_MAX_TIME ms.

[TEST_MAX_TIME] add max time control of test

---

iotdb-1.1/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb110/IoTDBClusterSession.java
iotdb-1.1/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb110/IoTDBSession.java

When IS_DELETE_DATA=true, drop the template named "TEMPLATE_NAME" when cleaning up the data.

Drop schema template when cleaning up (for iotdb1.1)

---

iotdb-1.1/pom.xml

Fixed compilation issues caused by relying on a deleted snapshot version

---

iotdb-1.1/src/assembly/assembly.xml
pom.xml

Display some information in git.properties, including
```
#Generated by Git-Commit-Id-Plugin
git.build.time=2023-07-31_12\:25\:08  CST
git.commit.id.abbrev=ee53bf6
git.dirty=true
```
For iotdb1.1 only.

Display information in git.properties

---

configuration/conf/README-cn.md
configuration/conf/README.md
core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/ConfigDescriptor.java

The combination of "DEVICE_NUM_PER_WRITE > 1" and "IS_SENSOR_TS_ALIGNMENT == false" is not supported

For MultiDeviceBatch, check IS_SENSOR_TS_ALIGNMENT in ConfigDescriptor

---

tdengine/README.md

The Readme for TDengine lacked sufficient detail, so I have added some additional descriptions to make it easier to use iot-benchmark for testing going forward.

Enhance the TDengine readme with more details

---

configuration/benchmark.sh
configuration/bin/startup.sh
core/src/main/java/cn/edu/tsinghua/iot/benchmark/App.java

Add some parameters before startup:
```shell
usage: benchmark.sh [-cf configuration_file] [-heapsize HEAP_SIZE] [-maxheapsize MAX_HEAP_SIZE]
-h           Show help.
-cf          Specify configuration file.
-heapsize    Specify HEAP_SIZE.
-maxheapsize Specify MAX_HEAP_SIZE.
example: ./benchmark.sh -cf conf/config.properties -heapsize 1G -maxheapsize 2G
```
You can also set memory by changing the configuration file.
```
#MAX_HEAP_SIZE="2G"
#HEAP_NEWSIZE="2G"
```

Add some parameters before startup

---

iotdb-1.1/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb110/ISessionDataSet.java
iotdb-1.1/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb110/IoTDBClusterSession.java
iotdb-1.1/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb110/IoTDBSession.java
iotdb-1.1/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb110/IoTDBSessionBase.java

For the case that we don't need to verify the correctness of the result, we should use DataIterator to iterate the ResultSet instead of using `SessionDataSet.next()` which will cause unnecessary overhead for constructing `RowRecord`, this may be nonnegligible while the result set is very large.

Optimize IoTDB iterate way

---

core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/ConfigDescriptor.java
core/src/main/java/cn/edu/tsinghua/iot/benchmark/measurement/Measurement.java
core/src/main/java/cn/edu/tsinghua/iot/benchmark/mode/BaseMode.java
iotdb-1.1/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb110/IoTDB.java
iotdb-1.1/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb110/IoTDBSessionBase.java

To prevent integer overflow from too many data points in one query.

Fix some bugs

---

iotdb-1.1/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb110/IoTDBSession.java

Previously, we only use first hostname for Session mode, this will cause error continuing throwing if we kill one node in iotdb cluster.
So we need to use nodeurls in sessio mode.
Before:
After:

Support nodeurls in session mode

---

core/src/main/java/cn/edu/tsinghua/iot/benchmark/tsdb/enums/DBSwitch.java

Now if db_switch is invalid, benchmark will use 012 as default. This is bad for debugging. 
So, throw an exception instead.

Throw exception when DB_SWITCH is invalid

---

configuration/conf/config.properties
core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/Config.java
core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/ConfigDescriptor.java
core/src/main/java/cn/edu/tsinghua/iot/benchmark/schema/MetaUtil.java
core/src/main/java/cn/edu/tsinghua/iot/benchmark/schema/schemaImpl/GenerateMetaDataSchema.java
core/src/main/java/cn/edu/tsinghua/iot/benchmark/schema/schemaImpl/RealMetaDataSchema.java
core/src/main/java/cn/edu/tsinghua/iot/benchmark/source/CSVDataReader.java
core/src/main/java/cn/edu/tsinghua/iot/benchmark/source/CopyDataReader.java
core/src/main/java/cn/edu/tsinghua/iot/benchmark/workload/GenerateQueryWorkLoad.java
core/src/main/java/cn/edu/tsinghua/iot/benchmark/workload/SingletonWorkDataWorkLoad.java
core/src/main/java/cn/edu/tsinghua/iot/benchmark/workload/SyntheticDataWorkLoad.java
iotdb-0.12/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb012/IoTDB.java
iotdb-0.13/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb013/IoTDB.java
iotdb-1.0/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb100/IoTDB.java
iotdb-1.1/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb110/IoTDB.java
tdengine-3.0/src/main/java/cn/edu/tsinghua/iot/benchmark/tdengine3/TDengine.java
tdengine/src/main/java/cn/edu/tsinghua/iot/benchmark/tdengine/TDengine.java
timescaledb-cluster/src/main/java/cn/edu/tsinghua/iot/benchmark/timescaledbCluster/TimescaleDB.java
timescaledb/src/main/java/cn/edu/tsinghua/iot/benchmark/timescaledb/TimescaleDB.java

Old configuration makes all devices have the same tag.
```
```
New configuration automatically generates different tags for different devices. Tags will be generated based on the hash value of the deviceName.
```
```
For example：
```
TAG_NUMBER=3
TAG_KEY_PREFIX=tag_
TAG_VALUE_PREFIX=value_
TAG_VALUE_CARDINALITY=50,50,10
```

Support variable tag in benchmark

---

core/src/main/java/cn/edu/tsinghua/iot/benchmark/measurement/persistence/csv/CSVRecorder.java
iotdb-1.1/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb110/IoTDBClusterSession.java
iotdb-1.1/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb110/IoTDBSession.java
iotdb-1.1/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb110/IoTDBSessionBase.java

https://jira.infra.timecho.com:8443/projects/BENCHMARK/issues/BENCHMARK-7?filter=allopenissues

Fix a problem: benchmark won't quit when DataNode accidently shutdown

---

iotdb-1.1/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb110/IoTDB.java

In the past, the last part of the schemaList that is less than the ACTIVATE_TEMPLATE_THRESHOLD will not be activated.

Fix bug of activating template

---

core/src/main/java/cn/edu/tsinghua/iot/benchmark/App.java
core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/ConfigDescriptor.java
core/src/main/java/cn/edu/tsinghua/iot/benchmark/mode/BaseMode.java
core/src/main/java/cn/edu/tsinghua/iot/benchmark/mode/GenerateDataMode.java
core/src/main/java/cn/edu/tsinghua/iot/benchmark/mode/TestWithDefaultPathMode.java
core/src/main/java/cn/edu/tsinghua/iot/benchmark/mode/VerificationQueryMode.java
core/src/main/java/cn/edu/tsinghua/iot/benchmark/mode/VerificationWriteMode.java
core/src/main/java/cn/edu/tsinghua/iot/benchmark/workload/SingletonWorkDataWorkLoad.java
core/src/main/java/cn/edu/tsinghua/iot/benchmark/workload/SyntheticDataWorkLoad.java
iotdb-1.1/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb110/IoTDB.java

Fix the Out Of Memory issue in Benchmark caused by creating a large number of devices using templates.

Support "register schema only" by set LOOP=0

---

cnosdb/src/main/java/cn/edu/tsinghua/iot/benchmark/cnosdb/CnosConnection.java
configuration/conf/config.properties
core/src/main/java/cn/edu/tsinghua/iot/benchmark/client/DataClient.java
core/src/main/java/cn/edu/tsinghua/iot/benchmark/client/SchemaClient.java
core/src/main/java/cn/edu/tsinghua/iot/benchmark/client/generate/GenerateDataDeviceClient.java
core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/Config.java
core/src/main/java/cn/edu/tsinghua/iot/benchmark/conf/ConfigDescriptor.java
core/src/main/java/cn/edu/tsinghua/iot/benchmark/measurement/persistence/mysql/MySqlRecorder.java
core/src/main/java/cn/edu/tsinghua/iot/benchmark/mode/BaseMode.java
core/src/main/java/cn/edu/tsinghua/iot/benchmark/schema/MetaDataSchema.java
core/src/main/java/cn/edu/tsinghua/iot/benchmark/schema/MetaUtil.java
core/src/main/java/cn/edu/tsinghua/iot/benchmark/schema/schemaImpl/DeviceSchema.java
core/src/main/java/cn/edu/tsinghua/iot/benchmark/schema/schemaImpl/GenerateMetaDataSchema.java
core/src/main/java/cn/edu/tsinghua/iot/benchmark/schema/schemaImpl/RealMetaDataSchema.java
core/src/main/java/cn/edu/tsinghua/iot/benchmark/source/CSVDataReader.java
core/src/main/java/cn/edu/tsinghua/iot/benchmark/source/CSVSchemaReader.java
core/src/main/java/cn/edu/tsinghua/iot/benchmark/source/CopyDataReader.java
core/src/main/java/cn/edu/tsinghua/iot/benchmark/workload/DataWorkLoad.java
core/src/main/java/cn/edu/tsinghua/iot/benchmark/workload/SingletonWorkDataWorkLoad.java
core/src/test/java/cn/edu/tsinghua/iot/benchmark/serialize/BatchSerializeTest.java
iotdb-1.0/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb100/IoTDB.java
iotdb-1.1/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb110/IoTDB.java
iotdb-1.3/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb130/IoTDB.java
iotdb-2.0/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb200/ModelStrategy/IoTDBModelStrategy.java
iotdb-2.0/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb200/ModelStrategy/TableStrategy.java
iotdb-2.0/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb200/ModelStrategy/TreeStrategy.java
tdengine-3.0/src/main/java/cn/edu/tsinghua/iot/benchmark/tdengine3/TDengine.java
timescaledb-cluster/src/main/java/cn/edu/tsinghua/iot/benchmark/timescaledbCluster/TimescaleDB.java
timescaledb/src/main/java/cn/edu/tsinghua/iot/benchmark/timescaledb/TimescaleDB.java

大多数改动是用上面的两个参数替换 CLIENT_NUMBER 。
1.之前用CLIENT_DATA_SCHEMA存储每个 client 负责的 deviceSchema。
现在用SCHEMA_CLIENT_DATA_SCHEMA存储每个 schemaclient 负责的 deviceSchema，DATA_CLIENT_DATA_SCHEMA存储每个 dataClient 负责的 deviceSchema；使用 CLIENT_DATA_SCHEMA 的方法也随之扩展为两个。
2.为了兼容参数 CLIENT_NUMBER，加载参数时会先加载 SCHEMA_CLIENT_NUMBER 与 DATA_CLIENT_NUMBER，然后加载 CLIENT_NUMBER 的值并赋值给 SCHEMA_CLIENT_NUMBER 与 DATA_CLIENT_NUMBER，用 CLIENT_NUMBER 的值去覆盖 SCHEMA_CLIENT_NUMBER 与 DATA_CLIENT_NUMBER 的默认值。
3.增加函数 distributeDevices 负责为每一个 client 分配 deviceSchema 。按照 deviceIds 分配。
4.verificationWriteMode 模式下是将文件（eg: bigBatch_0.tcsv）分配给每一个 client，之前是随机分配，改为按照 deviceIds的顺序排序；
5.deviceIds 进行了两次排序，第一次让属于同一个 database 的 deviceId 相邻，第二次让俗语同一个 table 的 deviceId 相邻，从而保证表模型下，分配给同一个 dataClient 的 device 是属于同一个 table 的，这样表模型下每个 data client 只需要执行一次 use database.

Add parameters to control the number of schema clients.

---

iotdb-2.0/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb200/DMLStrategy/JDBCStrategy.java

deviceSchema.getDevicePath() returns group.device, which lacks the “root.test” prefix.

 Corrected SQL generation logic to prevent parsing errors

---

core/src/main/java/cn/edu/tsinghua/iot/benchmark/client/SchemaClient.java
core/src/main/java/cn/edu/tsinghua/iot/benchmark/mode/BaseMode.java
iotdb-2.0/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb200/ModelStrategy/TreeStrategy.java

- 当注册元数据方法抛出异常后，bm 卡死不退出。这是由于抛出异常的线程少走了一次 CyclicBarrier 的 await() ，导致其他线程一直处于等待状态。
将 device 均分给每个 schemaClient 创建，创建 template -> 创建 database -> 激活 template -> 创建时间序列，使用 template 元数据的流程存在顺序关系：
- 创建 template 只需一个线程执行一次即可，完成 template 创建后，其他线程再创建database；
- 激活 template 前要保证所有的 database 已被创建；
- 创建时间序列前，需要所有线程完成 template 的激活；
所以，此处使用 3 个 CyclicBarrier ：templateBarrier、schemaBarrier、activateTemplateBarrier。
1. 在 basemode 下设置 volatile stopAllSchemaClient，默认为 false, 当有创建元数据方法抛出异常后在 catch 中将其改为 true；
2. 使用 try finally 保证不论方法是否正确执行，都会执行 await();
3. 在每个 await() 下加上对 stopAllSchemaClient 的检查，当为 true 时，提前结束方法，从而结束当前线程；

The system shuts down automatically if the template creation fails.

---

iotdb-2.0/pom.xml
iotdb-2.0/src/main/java/cn/edu/tsinghua/iot/benchmark/iotdb200/ModelStrategy/TableStrategy.java

in table model, previously, we will call `ceate table` multi times corresponding to sensor number).
Currently, we will call `ceate table` one time for one table.
Previous time cost(about 6 min)
current time cost(about 1 s)
bm config:
```
IoTDB_DIALECT_MODE=table
LOOP=17
DEVICE_NUMBER=10000
SENSOR_NUMBER=1
INSERT_DATATYPE_PROPORTION=0:0:0:1:0:0:0:0:0:0
IS_OUT_OF_ORDER=false
BATCH_SIZE_PER_WRITE=10000
DEVICE_NUM_PER_WRITE=1
SCHEMA_CLIENT_NUMBER=1
```

Opt for schema create of table model
